<?php

namespace SmartCity\GeoBundle\Entity\Repository;


use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;


/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends EntityRepository
{

	/**
	 * Return city which like their title likes
	 * the specified string
	 *
	 * @param string $title
	 * @return array
	 */
	public function getCityLikeTitle($province_id, $title)
	{
	    $qb = $this->_em->createQueryBuilder('p');
	    $qb
	        ->select('c.id', 'c.title')
	        ->from('SmartCityGeoBundle:City', 'c')

	        ->andWhere(
	        	$qb->expr()->like('c.title', ':title'),
	        	$qb->expr()->eq('c.province', ':province_id')
	        )
	        ->setParameter('title', "%$title%")
	        ->setParameter('province_id', $province_id)

	        ->setMaxResults(35)
	        ->orderBy('c.id', 'ASC');

	    return $qb->getQuery()->getResult(Query::HYDRATE_ARRAY);
	}
}
