<?php

namespace SmartCity\GeoBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;


/**
 * ProvinceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProvinceRepository extends EntityRepository
{
	/**
	 * Return province which like their title likes
	 * the specified string
	 *
	 * @param string $title
	 * @return array
	 */
	public function getProvinceLikeTitle($title)
	{
	    $qb = $this->_em->createQueryBuilder('p');
	    $qb
	        ->select(
	        	'p.id', 
	        	'p.title',
	        	'p.title as text' // for select2 plugin
	        )
	        ->from('SmartCityGeoBundle:Province', 'p')
	        
	        ->andWhere(
	        	$qb->expr()->like('p.title', ':title')

	        )
	        ->setParameter('title', "%$title%")
	        ->orderBy('p.id', 'ASC');

	    return $qb->getQuery()->getResult(Query::HYDRATE_ARRAY);
	}
}
