smartCity_locale:
    resource:   "@SmartCityPanelBundle/Controller/LocaleController.php"
    type:       annotation
    prefix:     /language/{_locale}

smartCity_panel:
    resource:   "@SmartCityPanelBundle/Controller/DashboardController.php"
    type:       annotation
    prefix:     /

smartCity_panel_auth:
    resource:   "@SmartCityPanelBundle/Controller/AuthController.php"
    type:       annotation
    prefix:     /auth

smartCity_panel_action:
    resource:   "@SmartCityPanelBundle/Controller/ActionController.php"
    type:       annotation
    prefix:     /action

smartCity_panel_action_group:
    resource:   "@SmartCityPanelBundle/Controller/ActionGroupController.php"
    type:       annotation
    prefix:     /action-group

smartCity_panel_role:
    resource:   "@SmartCityPanelBundle/Controller/RoleController.php"
    type:       annotation
    prefix:     /role

smartCity_panel_user:
    resource:   "@SmartCityPanelBundle/Controller/UserController.php"
    type:       annotation
    prefix:     /user

smartCity_panel_province:
    resource:   "@SmartCityPanelBundle/Controller/ProvinceController.php"
    type:       annotation
    prefix:     /province

smartCity_panel_sensor:
    resource:   "@SmartCityPanelBundle/Controller/SensorController.php"
    type:       annotation
    prefix:     /sensor