services:
#    panel.example:
#        class: SmartCity\PanelBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    SmartCity.elastic.service:
        class: SmartCity\PanelBundle\Services\ElasticService
        arguments: ["%elastic_host%", "%elastic_port%", "%elastic_index%"]
