imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration

framework:
    #esi:             ~
    # translator:      { fallbacks: ["%locale%"] }
    translator:      { fallbacks: [fa] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id: null
        cookie_lifetime: 31536000 # one year
    fragments:       ~
    http_method_override: true

# ======================================================== Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'TetranzSelect2EntityBundle:Form:fields.html.twig'

    globals:
        platform_version: "0.1"
        project_name: "%project_name%"
        domain: "%domain%"

# ======================================================== Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    filters:
        cssrewrite: ~
        jsqueeze: ~
        scssphp:
            formatter: 'Leafo\ScssPhp\Formatter\Compressed'

# ======================================================== Bazinga Configuration
bazinga_js_translation:
    active_locales:
        - fa
        - en

# ======================================================== Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        server_version: "%database_server_version%"
        logging:  true
        charset:  utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        mapping_types:
            enum:       string
            set:        string
        types:
            phone_number: Misd\PhoneNumberBundle\Doctrine\DBAL\Types\PhoneNumberType
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true


# ======================================================== Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# ======================================================== VichUploader Configuration
vich_uploader:
    db_driver: orm
    twig:      true
    storage:   file_system # or gaufrette or flysystem

    mappings:
        user_image:
            uri_prefix:         /uploads/images/user/
            upload_destination: %kernel.root_dir%/../web/uploads/images/user/
            namer:              vich_uploader.namer_uniqid

            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true

# ======================================================== Liip_imagine configuration
liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: %kernel.root_dir%/../web
                cache_prefix: media/cache

    loaders:
        default:
            filesystem:
                data_root: %kernel.root_dir%/../web/

    driver:               gd
    cache:                default
    data_loader:          default
    default_image:        null
    controller:
        filter_action:         liip_imagine.controller:filterAction
        filter_runtime_action: liip_imagine.controller:filterRuntimeAction
    filter_sets:
        lg:
            quality : 98
            filters:
                thumbnail: { size: [1024, 632], mode: outbound }

        md:
            quality : 98
            filters:
                thumbnail: { size: [512, 316], mode: outbound }

        sm:
            quality : 98
            filters:
                thumbnail: { size: [300, 185], mode: outbound }

        xs:
            quality : 90
            filters:
                thumbnail: { size: [128, 79], mode: outbound }

        # Prototype
        name:
            quality:              70
            jpeg_quality:         ~
            png_compression_level:  ~
            png_compression_filter: ~
            animated:             false
            format:               ~
            cache:                ~
            data_loader:          ~
            default_image:        null
            filters:
                # Prototype
                name:                 []
            post_processors:
                # Prototype
                name:                 []


# ======================================================== stof doctrine configuration
stof_doctrine_extensions:
    default_locale: fa
    orm:
        default:
            timestampable: true

# ======================================================== fos elastic configuration
fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        bank:
          settings:
            index:
              analysis:
                analyzer:
                  my_analyzer:
                    type: snowball
                    language: English
          types:
            acount:
              properties:
                address: { boost: 10, analyzer: my_analyzer }
                firstname:
                lastname:
              persistence:
                driver: orm
                model: Acme\DemoBundle\Entity\Article
                provider: ~
                finder: ~
#          finder:
#            account
#            types:
#              account:
#                properties:
#                  address: string
#
