# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        legacy:
            id: smartCity.security.legacy_encoder
        default:
            algorithm: sha512
            encode_as_base64: false
            iterations: 2

    role_hierarchy:
            ROLE_ADMIN:       ROLE_USER
            ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]


# http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
#    providers:
#        in_memory:
#            memory: ~
    providers:
            main:
                entity: { class: SmartCityUserBundle:User }

    access_decision_manager:
            strategy: unanimous

    # access_denied_url: /


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(panel|profiler|wdt)|css|images|js)/
            security: false

        ##### Panel
        panel_login:
            pattern: ^/auth/login$
            host:    %domain%
            anonymous: ~

        panel_register:
            pattern: ^/auth/register$
            anonymous: ~

        # secures part of the application
        panel:
            pattern: ^/
            host:    %domain%
            # anonymous: ~
            form_login:
                login_path: panel_auth_login
                check_path: panel_auth_login_check
                csrf_token_generator: security.csrf.token_manager

            logout:
                path: panel_auth_logout
                target: panel_auth_login